name: HarvesterTools
version: ${project.version}
main: dev.nuer.harvest.HarvesterTools
author: Nuer
commands:
  h:
    usage: /<command>
    description: Type '/h help' for command help.
  harvest:
    usage: /<command>
    description: Type '/harvest help' for command help.