name: HarvesterTools
author: nbdSteve
version: 1.0-BETA
main: com.nbdsteve.harvestertools.HarvesterTools
commands:
  h:
    usage: /<command>
    description: Type '/h help' for command help.
  harvest:
    usage: /<command>
    description: Type '/harvest help' for command help.