name: HarvesterTools
version: 1.2.2-[MC-1.13+]
main: dev.nuer.harvest.HarvesterTools
author: Nuer
commands:
  h:
    usage: /<command>
    description: Type '/h help' for command help.
  harvest:
    usage: /<command>
    description: Type '/harvest help' for command help.